---

- name: Create node_exporter system group
  group:
    name: "{{ node_exporter_system_group }}"
    state: present
    system: true

- name: Create the node_exporter user
  user:
    name: "{{ node_exporter_system_user }}"
    groups: "{{ node_exporter_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    createhome: false

- name: Ensure Prometheus exporters directory exist
  file:
    path: "{{ node_exporter_install_dir }}"
    state: directory

- name: Create node_exporter folder
  file:
    path: "{{ node_exporter_install_dir }}/{{ node_exporter_name }}"
    state: directory

- name: Unarchive Exporter
  unarchive:
    remote_src: yes
    dest: "{{ node_exporter_install_dir }}"
    src: "{{ node_exporter_url }}"

- name: Create symlink to the current release
  file:
    src: "{{ node_exporter_binary }}"
    path: "{{ node_exporter_symlink }}"
    state: link
  notify: restart node_exporter
